name: platform_detect
version: 2.0.11
description: A lightweight library for detecting the running browser and OS
homepage: https://github.com/Workiva/platform_detect
documentation: https://www.dartdocs.org/documentation/platform_detect/latest

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.6.0
  pub_semver: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  test: ^1.16.0
  workiva_analysis_options: ^1.2.0
