name: platform_detect
description: A lightweight library for detecting the running browser and OS
version: 0.0.1
author: Workiva Client Platform Team <team-clientplatform@workiva.com>
homepage: https://github.com/Workiva/platform_detect
documentation: https://docs.workiva.org/platform_detect/latest/
publish_to: https://pub.workiva.org

environment:
  sdk: ">=1.12.1 <2.0.0"

dependencies:
  pub_semver: ^1.0.0

dev_dependencies:
  dart_style: 0.2.10
  coverage: ^0.7.9
  browser: any
  dart_dev: ^1.4.2
  test: ^0.12.0
